pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/jira-docker
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    build_args:
      - JIRA_VERSION=${JIRA_VERSION}
    tags:
      - ${JIRA_VERSION}
    when:
      event: push

matrix:
  JIRA_VERSION:
    - 7.2.4
    - 7.7.1
    - 7.7.0
    - 7.6.3
    - 7.6.2
    - 7.6.1
    - 7.6.0
    - 7.5.4
    - 7.5.3
    - 7.5.2
    - 7.5.1
    - 7.5.0
    - 7.4.6
    - 7.4.5
    - 7.4.4
    - 7.4.3
    - 7.4.2
    - 7.4.1
    - 7.4.0
    - 7.3.9
    - 7.3.8
    - 7.3.7
    - 7.3.6
    - 7.3.5
    - 7.3.4
    - 7.3.3