pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/jira-docker
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    force_tag: true
    build_args:
      - JIRA_VERSION=${JIRA_VERSION}
    tags:
      - ${JIRA_VERSION}
    when:
      event: push

matrix:
  JIRA_VERSION:
    - 7.12.0
    - 7.13.0
    - 8.0.0
